name: Update README

on:
  schedule:
    - cron: '*/01 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    - name: GitHub - Activity - Readme

    steps:
      - uses: actions/checkout@v2
        uses: williamthefatman/github-activity-readme@v0.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}